# Starter file. Add your own services (your app, Postgres) next to payswift. Leave payswift as it is.
services:
  payswift:
    build: ./payswift
    ports:
      - "8081:8081"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: quickdrop
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quickdrop_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: